source: phantomx_pincher_robot_arm_edited_gripper.yaml
port: /dev/ttyUSB0
read_rate: 10
write_rate: 10
joints: {
    # All min and max angles w.r.t. to the neutral angle: [neutral-min_angle, neutral+max_angle]
    # The neutral value is encoded according to the interval 0..1024
    # Min and max angles are in the range [-180,180] (deg)
    left_gripper_joint: {id: 5, max_angle: 0, min_angle: -145, max_speed: 90, type: prismatic, radius: .0078, connector: .024, offset: .016},
    #left_gripper_joint: {id: 5, neutral: 250, max_angle: 50, min_angle: -60, max_speed: 50, type: dynamixel}
    right_gripper_joint: {id: 8, max_angle: 0, min_angle: -145, max_speed: 90, type: prismatic, radius: .0078, connector: .024, offset: .016}
}
controllers: {
    gripper_controller: {type: follow_controller, joints: [left_gripper_joint,right_gripper_joint], action_name: gripper_controller/follow_joint_trajectory, onboard: False, rate: 50}
}
